services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile.back
    ports: 
      - "3000:3000"
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      pg-opokedex:
        condition: service_healthy
  
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.front
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - back

  pg-opokedex:
    build:
      context: ./
      dockerfile: Dockerfile.pg
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      start_period: 15s
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  db_data: { }
